import"./About.svelte.css.proxy.js";import{SvelteComponent as N,add_render_callback as O,append as o,attr as K,create_component as h,create_in_transition as Q,destroy_component as k,detach as d,element as g,init as V,insert as _,mount_component as w,safe_not_equal as W,space as T,text as s,transition_in as v,transition_out as b}from"../../_snowpack/pkg/svelte/internal.js";import{fade as X}from"../../_snowpack/pkg/svelte/transition.js";import x from"../components/Link.svelte.js";function Z(i){let t;return{c(){t=s("Home")},m(e,r){_(e,t,r)},d(e){e&&d(t)}}}function tt(i){let t;return{c(){t=s("Svelte")},m(e,r){_(e,t,r)},d(e){e&&d(t)}}}function et(i){let t;return{c(){t=s("TypeScript")},m(e,r){_(e,t,r)},d(e){e&&d(t)}}}function nt(i){let t;return{c(){t=s("nginx")},m(e,r){_(e,t,r)},d(e){e&&d(t)}}}function ot(i){let t;return{c(){t=s("GitHub")},m(e,r){_(e,t,r)},d(e){e&&d(t)}}}function st(i){let t,e,r,C,S,p,q,c,M,H,Y,y,L,G,a,I,$,P,u,R,f,U,m,z,A,j;return c=new x({props:{to:"#/",$$slots:{default:[Z]},$$scope:{ctx:i}}}),$=new x({props:{ext:!0,to:"https://svelte.dev",$$slots:{default:[tt]},$$scope:{ctx:i}}}),u=new x({props:{ext:!0,to:"https://typescriptlang.org",$$slots:{default:[et]},$$scope:{ctx:i}}}),f=new x({props:{ext:!0,to:"https://nginx.org",$$slots:{default:[nt]},$$scope:{ctx:i}}}),m=new x({props:{ext:!0,to:"https://github.com/wiisportsresort/pigeon-project",$$slots:{default:[ot]},$$scope:{ctx:i}}}),{c(){t=g("div"),e=g("h1"),e.textContent="About",r=T(),C=g("p"),C.innerHTML=`This is <strong>Pigeon</strong>, a mock social media website modeled after Twitter, Reddit, and
    the like, made for a school project. Users can make <strong>posts</strong> and
    <strong>comments</strong> in reply.`,S=T(),p=g("p"),q=s("You can start on the "),h(c.$$.fragment),M=s(` page and look through the list of latest posts there.
    Clicking on one will bring you to the posts's unique page (at `),H=g("code"),H.textContent="/#/post/<id>",Y=s(`),
    where you can view its comments.`),y=T(),L=g("p"),L.innerHTML=`Clicking on a profile image or the username on a post will bring you to their page (at <code>/#/user/&lt;username&gt;</code>). You can view their bio, followers/folowees, join date, posts, comments, and media posts
    there.`,G=T(),a=g("p"),I=s("I used "),h($.$$.fragment),P=s(` to make components, which were written in
    `),h(u.$$.fragment),R=s(`. Hosting is done with
    `),h(f.$$.fragment),U=s(`
    (many problems but eventually it worked). The source code is available at
    `),h(m.$$.fragment),z=s("."),K(t,"id","about"),K(t,"class","svelte-1v4j7lh")},m(n,l){_(n,t,l),o(t,e),o(t,r),o(t,C),o(t,S),o(t,p),o(p,q),w(c,p,null),o(p,M),o(p,H),o(p,Y),o(t,y),o(t,L),o(t,G),o(t,a),o(a,I),w($,a,null),o(a,P),w(u,a,null),o(a,R),w(f,a,null),o(a,U),w(m,a,null),o(a,z),j=!0},p(n,[l]){const B={};l&1&&(B.$$scope={dirty:l,ctx:n}),c.$set(B);const D={};l&1&&(D.$$scope={dirty:l,ctx:n}),$.$set(D);const E={};l&1&&(E.$$scope={dirty:l,ctx:n}),u.$set(E);const F={};l&1&&(F.$$scope={dirty:l,ctx:n}),f.$set(F);const J={};l&1&&(J.$$scope={dirty:l,ctx:n}),m.$set(J)},i(n){j||(v(c.$$.fragment,n),v($.$$.fragment,n),v(u.$$.fragment,n),v(f.$$.fragment,n),v(m.$$.fragment,n),A||O(()=>{A=Q(t,X,{duration:100}),A.start()}),j=!0)},o(n){b(c.$$.fragment,n),b($.$$.fragment,n),b(u.$$.fragment,n),b(f.$$.fragment,n),b(m.$$.fragment,n),j=!1},d(n){n&&d(t),k(c),k($),k(u),k(f),k(m)}}}class rt extends N{constructor(t){super();V(this,t,null,st,W,{})}}export default rt;
