/* src/components/Attribution.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let ul;

	return {
		c() {
			ul = element("ul");

			ul.innerHTML = `<li><a href="https://iconscout.com/icons/seagull" target="_blank">seagull</a>
    by
    <a href="https://iconscout.com/contributors/oviyan" target="_blank">Thanga Vignesh P</a></li>`;
		},
		m(target, anchor) {
			insert(target, ul, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(ul);
		}
	};
}

class Attribution extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Attribution;
//# sourceMappingURL=Attribution.js.map
