/* src/components/Icon.svelte generated by Svelte v3.31.2 */
import {
	HtmlTag,
	SvelteComponent,
	detach,
	empty,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../web_modules/svelte/internal.js";

import { icons } from "../../web_modules/feather-icons.js";

function create_fragment(ctx) {
	let html_tag;
	let html_anchor;

	return {
		c() {
			html_anchor = empty();
			html_tag = new HtmlTag(html_anchor);
		},
		m(target, anchor) {
			html_tag.m(/*svg*/ ctx[0], target, anchor);
			insert(target, html_anchor, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*svg*/ 1) html_tag.p(/*svg*/ ctx[0]);
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(html_anchor);
			if (detaching) html_tag.d();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	
	
	let { icon } = $$props;
	let { attrs = undefined } = $$props;
	let svg;

	$$self.$$set = $$props => {
		if ("icon" in $$props) $$invalidate(1, icon = $$props.icon);
		if ("attrs" in $$props) $$invalidate(2, attrs = $$props.attrs);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*icon, attrs*/ 6) {
			$: $$invalidate(0, svg = icon ? icons[icon].toSvg(attrs) : "");
		}
	};

	return [svg, icon, attrs];
}

class Icon extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { icon: 1, attrs: 2 });
	}
}

export default Icon;
//# sourceMappingURL=Icon.js.map
